baseURL = 'https://rebelzion.github.io/'
languageCode = 'en-us'
title = 'On machines & matter'
theme = 'paper'
disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # add disqus comments
features = ["Responsive", "One Column", "Blog"]


 # needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
 [markup]
   [markup.goldmark]
     [markup.goldmark.renderer]
       unsafe = true
 
 [menu]
 
   [[menu.main]]
     identifier = "about"
     name = "About"
     url = "/about/"
     weight = 10
   [[menu.main]]
     identifier = "contact"
     name = "Contact"
     url = "/contact/"
     weight = 10

 [taxonomies]
 category = "categories"
 tag = "tags"
 series = "series"

 [privacy]

   [privacy.vimeo]
     disabled = false
     simple = true

   [privacy.twitter]
     disabled = false
     enableDNT = true
     simple = true

   [privacy.instagram]
     disabled = false
     simple = true

   [privacy.youtube]
     disabled = false
     privacyEnhanced = true

 [services]

   [services.instagram]
     disableInlineCSS = true

   [services.twitter]
     disableInlineCSS = true

[author]
  name = "rebelzion"

[params]
  # color style
  color = 'wheat'                 # linen, wheat, gray, light

  # header social icons
  twitter = 'YOUR_TWITTER_ID'     # twitter.com/YOUR_TWITTER_ID
  github = 'rebelzion'       # github.com/YOUR_GITHUB_ID
  instagram = 'YOUR_INSTAGRAM_ID' # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                      # show rss icon with link

  # home page profile
  avatar = 'GRAVATAR_EMAIL'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
  name = 'Rebelzion'
  bio = 'Machine Learning Engineer'

  # misc
  disableHLJS = true              # disable requesting highlight.js
  monoDarkIcon = false             # show monochrome dark mode icon
